Repository LeonardoCalazans/Jogo-da-Velha, pull requests merged in 2022-04, with the labels that each got.

#2 Feature/nygma01 - Finalizado Lógica do jogo
  css/endGame/winner.css
  css/gameplay/boardgaming.css
  css/themes/colors.css
  index.html
  main-OLD.js
  main.js
  modules/buttonPlay.js
  modules/checkEndGame.js
  modules/checkForDraw.js
  modules/checkForWin.js
  modules/createCells.js
  modules/endGame.js
  modules/handleClick.js
  modules/placeMark.js
  modules/restartGame.js
  modules/setBoardHoverClass.js
  modules/setPlayers.js
  modules/showRecords.js
  modules/startGame.js
  modules/swapTurn.js
  records.html
  records.js
Labels: enhancement

#4 [BUGFIX] - Fix contagem de pontos e exibição de histórico
  main-OLD.js
  records.html
  records.js
Labels: bug

#5 Leonardo/feat/adding new colors
  css/endGame/records.css
  css/gameplay/board.css
  css/login/login.css
  css/themes/button.css
  css/themes/colors.css
  css/themes/general-style.css
  index.html
  main-OLD.js
  main.js
  modules/setColors.js
  records.html
  records.js
Labels: bug, enhancement
